[build]
target = "x86_64-pc-windows-gnu"

[target.x86_64-pc-windows-gnu]
linker = "C:\\dev\\bevy\\.toolchains\\w64devkit\\bin\\gcc.exe"
rustflags = [
    "-C",
    "link-self-contained=no",
    "-C",
    "dlltool=C:\\dev\\bevy\\.toolchains\\w64devkit\\bin\\dlltool.exe",
    "-C",
    "link-arg=-BC:\\dev\\bevy\\.toolchains\\w64devkit\\bin\\",
]
